global:
  scrape_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'nginx_exporter'
    static_configs:
      - targets: ['nginx_exporter:9113']


alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]  # Connects to Alertmanager
