version: '3.3'

services:
  web1:
    image: nginx:alpine
    volumes:
      - ./web1:/usr/share/nginx/html
    networks:
      - webnet

  web2:
    image: nginx:alpine
    volumes:
      - ./web2:/usr/share/nginx/html
    networks:
      - webnet

  load_balancer:
    build:
      context: ./nginx-loadbalancer
    privileged: true
    volumes:
      - ./nginx-loadbalancer/nginx.conf:/etc/nginx/nginx.conf
    command: ["/bin/sh", "-c", "/usr/local/bin/iptables-rules.sh && nginx -g 'daemon off;'"]
    ports:
      - "80:80"
    networks:
      - webnet
    cap_add:
      - NET_ADMIN

  attacker:
    build:
      context: ./attacker
    depends_on:
      - load_balancer
    networks:
      - webnet

networks:
  webnet:
