version: '3.3'

services:
  web1:
    image: nginx:alpine
    volumes:
      - ./web1:/usr/share/nginx/html
    networks:
      - webnet

  web2:
    image: nginx:alpine
    volumes:
      - ./web2:/usr/share/nginx/html
    networks:
      - webnet

  load_balancer:
    image: nginx:alpine
    volumes:
      - ./nginx-loadbalancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - webnet

  attacker:
    build:
      context: ./attacker
    depends_on:
      - load_balancer
    networks:
      - webnet

networks:
  webnet:
