version: '3.3'

services:
  web1:
    image: nginx:alpine
    volumes:
      - ./web1:/usr/share/nginx/html
    networks:
      - webnet

  web2:
    image: nginx:alpine
    volumes:
      - ./web2:/usr/share/nginx/html
    networks:
      - webnet

  load_balancer:
    build:
      context: ./nginx-loadbalancer
    privileged: true
    volumes:
      - ./nginx-loadbalancer/nginx.conf:/etc/nginx/nginx.conf
    command: ["/bin/sh", "-c", "/usr/local/bin/iptables-rules.sh && nginx -g 'daemon off;'"]
    ports:
      - "80:80"
    networks:
      - webnet
    cap_add:
      - NET_ADMIN

  attacker:
    build:
      context: ./attacker
    depends_on:
      - load_balancer
    networks:
      - webnet

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - webnet

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - webnet

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    ports:
      - "9113:9113"
    networks:
      - webnet
    command:
      - -nginx.scrape-uri=http://load_balancer/stub_status

volumes:
  grafana-data:

networks:
  webnet:
